apiVersion: apps/v1
kind: Deployment
metadata:
  name: purple
spec:
  selector:
    matchLabels:
      app: purple
  replicas: 2
  template:
    metadata:
      labels:
        app: purple
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
