apiVersion: apps/v1
kind: Deployment
metadata:
  name: orange
spec:
  selector:
    matchLabels:
      app: orange
  replicas: 2
  template:
    metadata:
      labels:
        app: orange
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80