apiVersion: v1
kind: Pod
metadata:
  name: nginx-github
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
  # These containers are run during pod initialization
  initContainers:
  - name: gitclone
    image: alpine/git
    command:
    - git
    - clone
    - https://github.com/tiffanyfay/space-app.git
    volumeMounts:
    - name: workdir
      mountPath: "/space-app"
  dnsPolicy: Default
  volumes:
  - name: workdir
    emptyDir: {}